# Generated by Django 2.1.2 on 2018-12-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181223_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
